test/telegrambot_lib/config_test.clj, test/telegrambot_lib/core_test.clj, test/telegrambot_lib/http_test.clj
Added initial unit tests for core, config, http namespaces.
Closes #1
=> issue/1/unit-tests: Initial Unit Tests

.github/workflows/clojure.yml
Initial github pipeline.
Closes #3
=> issue/3/pipeline: Pipeline Setup

src/telegrambot_lib/edit/params.clj
New records to define the parameters required and optional for the edit namespace functions.
Closes #7
=> Parameter records for edit ns

src/telegrambot_lib/inline/params.clj
New parameter records for functions in the inline namespace.
Closes #9
=> Parameter records for inline namespace.

src/telegrambot_lib/passport/params.clj
New parameter records for functions in the passport namespace.
Closes #11
=> Parameter records for the passport namespace.

src/telegrambot_lib/passport/params.clj, src/telegrambot_lib/payments/params.clj
New parameter records for the functions in the payments namespace.
Also corrected record name in passport params.
=> Parameter records for payments namespace.

src/telegrambot_lib/stickers/params.clj
New parameter records for the functions in the stickers namespace.
Closes #13
=> Parameter records for the stickers namespace.

src/telegrambot_lib/updates/params.clj
New parameter records for the functions in the updates namespace.
Closes #14
=> Parameter records for updates namespace.

src/telegrambot_lib/methods/params.clj
New parameter records for the functions in the methods namespace.
=> Parameter records for methods namespace.

README.md, src/telegrambot_lib/config.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/methods/core.clj
Added multi-arity parameters to functions in the methods namespace.
Updated documentation.
Closes #26
=> issue/26/req-opt-params-methods-ns: Function req/optional parameters - methods namespace

src/telegrambot_lib/core.clj, src/telegrambot_lib/edit/core.clj
Added multi-arity parameters to functions in the edit namespace.
Closes #23
=> issue/23/req-opt-params-edit-ns: Function req/optional parameters - edit namespace

src/telegrambot_lib/core.clj, src/telegrambot_lib/games/core.clj
Added multi-arity parameters for req/opt params in the games namespace.
Closes #24
=> issue/24/req-opt-params-games-ns: Function req/optional parameters - games namespace

src/telegrambot_lib/inline/core.clj
New multi-arity parameters for functions in the inline namespace.
Closes #25
=> issue/25/req-opt-params-inline-ns: Function req/optional parameters - inline namespace

src/telegrambot_lib/games/core.clj, src/telegrambot_lib/inline/core.clj, src/telegrambot_lib/passport/core.clj
New multi-arity parameters for functions in the passport namespace.
Closes #27
=> issue/27/req-opt-params-passport-ns: Function req/optional parameters - passport namespace

src/telegrambot_lib/core.clj, src/telegrambot_lib/payments/core.clj
New multi-arity parameters for the functions in the payments namespace.
Closes #28
=> issue/28/req-opt-params-payments-ns: Function req/optional parameters - payments namespace

src/telegrambot_lib/stickers/core.clj
New multi-arity parameters for functions in the stickers namespace.
Closes #29
=> issue/29/req-opt-params-stickers-ns: Function req/optional parameters - stickers namespace

src/telegrambot_lib/updates/core.clj
New multi-arity parameters for functions in the updates namespace.
Closes #30
=> issue/30/req-opt-params-updates-ns: Function req/optional parameters - updates namespace

src/telegrambot_lib/passport/core.clj, src/telegrambot_lib/passport/params.clj, src/telegrambot_lib/passport/protocol.clj
- Converted params record to fn docstrings.
- Updated protocol to match fn signatures.
Closes #43
=> issue/43/docstrings-passport: records->docstrings - passport ns

CHANGELOG.md, README.md, project.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/edit/core.clj, src/telegrambot_lib/games/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj, src/telegrambot_lib/payments/core.clj, src/telegrambot_lib/stickers/core.clj, src/telegrambot_lib/updates/core.clj, src/telegrambot_lib/updates/protocol.clj
New methods implemented:
- logOut
- close
- unpinAllChatMessages
- copyMessage
Closes #55
=> issue/55/bot-api-5-updates: Review/Implement Bot API 5.0 Changes

README.md, doc/intro.md, src/telegrambot_lib/config.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/edit/core.clj, src/telegrambot_lib/edit/protocol.clj, src/telegrambot_lib/games/core.clj, src/telegrambot_lib/games/protocol.clj, src/telegrambot_lib/http.clj, src/telegrambot_lib/inline/core.clj, src/telegrambot_lib/inline/protocol.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj, src/telegrambot_lib/passport/core.clj, src/telegrambot_lib/passport/protocol.clj, src/telegrambot_lib/payments/core.clj, src/telegrambot_lib/payments/protocol.clj, src/telegrambot_lib/stickers/core.clj, src/telegrambot_lib/stickers/protocol.clj, src/telegrambot_lib/updates/core.clj, src/telegrambot_lib/updates/protocol.clj
Added markdown lists to all functions to improve cljdoc generated readability.
Minor project intro updates to doc intro and readme.
Closes #57
=> issue-57: Improve function docstrings with markdown

src/telegrambot_lib/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj
- Added new methods to methods.core ns: create-chat-invite-link, edit-chat-invite-link, revoke-chat-invite-link.
- Added new optional parameters to function docstrings.
Closes #60
=> issue-60: Review/Implement Bot API 5.1 Changes

CHANGELOG.md, README.md, project.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/payments/core.clj, src/telegrambot_lib/payments/protocol.clj
- Bot API 5.2 support: optional param updates for payments.
- Project dependency version updates.
Closes #63
=> issue-63: Review/Implement Bot API 5.2 Changes

CHANGELOG.md, README.md, project.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj
- Add optional parameters (scope, language_code) to the method: [setMyCommands](https://core.telegram.org/bots/api#setmycommands)
- Add optional parameters (scope, language_code) to the method: [getMyCommands](https://core.telegram.org/bots/api#getmycommands)
- Add new method: [deleteMyCommands](https://core.telegram.org/bots/api#deletemycommands)
- Method renamed from "kickChatMember" to "[banChatMember](https://core.telegram.org/bots/api#banchatmember)".
- Method renamed from "getChatMembersCount" to "[getChatMemberCount](https://core.telegram.org/bots/api#getchatmembercount)"
Closes #66
=> issue-66: Review/Implement Bot API 5.3 Changes

CHANGELOG.md, project.clj
Release to include fixes for:
- #68
- #69
=> Minor release prep for method bug fixes.

src/telegrambot_lib/http.clj
Hi Bill!
As we previously agreed in #72, it would be good to make the sync `request` fn handle responses to unsuccessful Telegram Bot API requests the same way as the async version does it.
I've tested this new behavior locally with a draft lib version and here's what the result looks like. For instance, if you try to omit a required `url` param while requesting to `setWebhook`:
```clojure
(tbot/set-webhook (tbot/create token) nil)
=>
{:ok false,
:error_code 400,
:description "Bad Request: bad webhook: Failed to resolve host: No address associated with hostname",
:error #error{...}}
```
The lib user now have a choice:
- to just log (w/ `:error_code` and `:description`), or 
- to retry (if the `:parameters` as present), or 
- to rethrow the `:error` (why not?).
And I think now is a good …
=> Align the 'request' fns contracts

env/dev/resources/logback.xml, env/test/resources/logback.xml, project.clj, src/telegrambot_lib/config.clj, src/telegrambot_lib/http.clj
Here's the logging part of the deal.
=> Elude the logging implementation dependency (part of #76)

.github/workflows/clojure.yml, project.clj, src/telegrambot_lib/http.clj, src/telegrambot_lib/json.clj, test/telegrambot_lib/json_test.clj
Here's the JSON mapping part of the deal.
=> Elude the JSON mapper dependency (part of #76)

CHANGELOG.md, project.clj
- Release 1.0.0 prep.
Part of #75
=> issue-75: Release 1.0.0

README.md
Pardon for being a bit late to the party. Just have found minor inconsistencies in the README. No version bump required.
=> Misc README.md fixes for 1.0.0

CHANGELOG.md, project.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj
- New optional parameters, name and creates_join_request for method createChatInviteLink
- New optional parameters, name and creates_join_request for method editChatInviteLink
- New method approveChatJoinRequest
- New method declineChatJoinRequest
- Updated sendChatAction's action parameter description to include new action, choose_sticker.
- Dependency and project version bumps.
Closes #85
=> issue-85: Review/Implement Bot API 5.4 Changes

CHANGELOG.md, project.clj, src/telegrambot_lib/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/methods/protocol.clj
- Added new methods: ban-chat-sender-chat, unban-chat-sender-chat.
- Project dependency version bumps.
- Release prep.
Closes #88
=> issue-88: Review/Implement Bot API 5.5 Changes

CHANGELOG.md, project.clj, src/telegrambot_lib/games/core.clj, src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/payments/core.clj, src/telegrambot_lib/stickers/core.clj
- New parameter, protect_content for methods: sendMessage, sendPhoto,
sendVideo, sendAnimation, sendAudio, sendDocument, sendSticker,
sendVideoNote, sendVoice, sendLocation, sendVenue, sendContact,
sendPoll, sendDice, sendInvoice, sendGame, sendMediaGroup,
copyMessage, forwardMessage.
- Bumped project version dependencies.
Closes #90
=> issue-90: Review/Implement Bot API 5.6 Changes

CONTRIBUTING.md
- Added initial contributing file, with notes on what telegram bot api changes require library changes.
=> Initial CONTRIBUTING

CHANGELOG.md, CONTRIBUTING.md
- Minor markdown lint and spelling fixes in Contributing.
- Added contributing to the changelog.
=> Minor contrib fixes

README.md
- Updated the license year range to reflect 2022.
=> License year update.

pom.xml, project.clj, src/telegrambot_lib/stickers/core.clj
- Updated docstrings for a new optional parameter, webm_sticker.
- Project and lib dependency version bumps.
Closes #103
=> issue-103: Review/Implement Bot API 5.7 Changes

README.md, pom.xml
- Updated clojure badge version in README.
- Generated updated pom.
=> clj-badge-version

src/telegrambot_lib/methods/core.clj, src/telegrambot_lib/payments/core.clj, src/telegrambot_lib/predicates.clj, src/telegrambot_lib/stickers/core.clj, src/telegrambot_lib/updates/core.clj
- Created new predicates namespace.
- Moved content-map? fn to this namespace, as it was duplicated in
multiple locations.
=> predicates-ns

.github/workflows/clojure.yml
Target only jdk LTS versions in the pipeline.
=> jdk-versions

.github/workflows/clojure.yml, Makefile, pom.xml, project.clj, src/telegrambot_lib/api/payments.clj, src/telegrambot_lib/api/updates.clj, src/telegrambot_lib/core.clj, test/telegrambot_lib/http_test.clj
- New method: [payments/createInvoiceLink](https://core.telegram.org/bots/api#createinvoicelink)
- New optional parameter, secret_token, added to [updates/setWebhook](https://core.telegram.org/bots/api#setwebhook)
- Dependency, project version bumps. Generated new pom.
- New Makefile with targets for building, testing, packaging, deploying, and debug info.
=> issue-114: Review/Implement Bot API 6.1 Changes

pom.xml, project.clj, src/telegrambot_lib/api/stickers.clj, src/telegrambot_lib/core.clj
- New method api/stickers/get-custom-emoji-stickers.
- Updated optional parameters for api/stickers/create-new-sticker-set.
(removed contains_masks, added sticker_type)
- Project version bump.
Closes #117
=> issue-117: Review/Implement Bot API 6.2 Changes

.github/workflows/clojure.yml, pom.xml, project.clj, src/telegrambot_lib/api/games.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/api/payments.clj, src/telegrambot_lib/api/stickers.clj, src/telegrambot_lib/core.clj
- New methods and optional parameters in support of bot api 6.3.
- Package dependency updates.
- Version bump.
Closes #119
=> issue-119: Review/Implement Bot API 6.3 Changes

Makefile, pom.xml, project.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/core.clj
- Updated optional parameters in docstrings.
- WARNING: edit-forum-topic fn signature changed if using the only required parameters arity, in direct support of bot api 6.4 changes.
- New methods for bot api 6.4
- Updated pom.
- Version bump.
Closes #121
=> issue-121: Review/Implement Bot API 6.4 Changes

pom.xml, project.clj, src/telegrambot_lib/api/methods.clj
- New optional parameters for bot api 6.5.
- Version bump and pom updated.
Closes #123
=> issue-123: Review/Implement Bot API 6.5 Changes

pom.xml, project.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/api/stickers.clj, src/telegrambot_lib/core.clj
- New methods in support of bot api 6.6.
- Project version bump.
- New optional parameters for bot api 6.6.
- Required and optional parameter changes for bot api 6.6.
- pom regenerated.
Closes #125
=> issue-125: Review/Implement Bot API 6.6 Changes

pom.xml, project.clj, src/telegrambot_lib/api/inline.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/core.clj, test/telegrambot_lib/http_test.clj
- New functions in api/methods.
- Changed optional parameters in api/inline/answer-inline-query.
- Fixed un-used binding warning in http_test.
- Project and clj-http-fake version bumps.
Closes #129
=> issue-129: Review/Implement Bot API 6.7 Changes

env/dev/fiddles/telegrambot_lib/core.clj
Added a calva fiddle file for quickly executing a live bot create, info, and message send test.
=> dev tool - fiddle file for core.

pom.xml, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/core.clj
- New function, unpin-all-general-forum-topic-messages.
Closes #134
=> issue-134: Review/Implement Bot API 6.8 Changes

README.md, pom.xml, project.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/http.clj
- docstring updates in methods/promote-chat-member due to new optional parameters.
- project version bump.
Closes #141
=> issue-141: Review/Implement Bot API 6.9 Changes

README.md, pom.xml, project.clj, src/telegrambot_lib/api/edit.clj, src/telegrambot_lib/api/games.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/api/payments.clj, src/telegrambot_lib/api/stickers.clj, src/telegrambot_lib/core.clj
- Optional parameter replacements. (disable_web_page_preview with link_preview_options)
- Project and dependency version bumps.
- Readme updates to include github pages and update License years.
Closes #145
=> issue-145: Review/Implement Bot API 7.0 Changes

README.md
Updating the main readme to include a link to the api generated docs.
=> Updated readme with api docs link.

Makefile, pom.xml, project.clj, src/telegrambot_lib/api/games.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/api/stickers.clj, src/telegrambot_lib/core.clj, test/telegrambot_lib/http_test.clj
Changes in support of bot api 7.2 release.
- New method, get-business-connection.
- New method, replace-sticker-in-set.
- Removed the once required parameter, sticker_format, from fn create-new-sticker-set.
- Added new required parameter, format, to fn set-sticker-set-thumbnail.
- Added new optional parameter, business_connection_id, to a number of send fns across the methods, games, and stickers api namespaces.
Project maintenance changes
- Project dependencies and version bump.
- Changed default dev and test profile json lib to org.clojure/data.json due to minimal deps that don't clash with other json mapper libs.
Closes #151
=> issue-151: Review/Implement Bot API 7.2 Changes

README.md, pom.xml, project.clj, src/telegrambot_lib/api/methods.clj, src/telegrambot_lib/core.clj
- Updated fns for the telegram bot api 7.3 release.
- Bumped project and dependency versions.
- Generated pom.
- Minor readme updates for usage docs section.
Closes #156
=> issue-156: Review/Implement Bot API 7.3 Changes
